### ISSUE TITLE
'How does promissions work?

### ISSUE THREAD

**Issue by iDamian505** [MasahiroSaito/Homes#1]

**Comment by MasahiroSaito** [comment]
Write Permission in the permissions.yml of the server, or install PermissionEx and make the setting.

> - [[Bukkit guide] Permissions](https://bukkit.org/threads/bukkit-guide-permissions.50305/)
> - [PermissionsEx](https://dev.bukkit.org/projects/permissionsex)

**Comment by MasahiroSaito** [comment]
Information of Homes permissions is [here](https://github.com/MasahiroSaito/Homes/wiki/Permissions)

**Comment by iDamian505** [comment]
Thank you

Op 7 mrt. 2017 15:18 schreef "Masahiro Saito" <notifications@github.com>:
